# ETAPA 1: Builder (Instalación de dependencias)
FROM python:3.9-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# ETAPA 2: Producción (Imagen liviana final en Alpine)
FROM python:3.9-alpine

WORKDIR /app

# Copiar dependencias instaladas desde la etapa builder
COPY --from=builder /root/.local /root/.local
COPY app.py .

# Agregar las dependencias al PATH de la imagen Alpine
ENV PATH=/root/.local/bin:$PATH
EXPOSE 5000

CMD ["python", "app.py"]
